# Site settings
title: spaceboats
#email: your_email@example.com
#author: 
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl: ""
url: "http://spaceboats.github.io"
#google_analytics:
animated: false
show_related_posts: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true
